### ISSUE TITLE
Navigate from new entity to document

### ISSUE THREAD

**Issue by benwbrum** [CivilWarGovernorsOfKentucky/Mashbill#1] opened 2016-09-26 18:56 UTC
- View a document
- Identify an annotation
- Create an entity
- See the `entitiy#show` action with _Entity was successfully created._ success message
- Now how do I get back to what I was doing?

**Comment by saracarl** [comment] 2017-02-02 19:48
Duplicate of Issue #5

**Closed** 2017-02-02 19:49 UTC
Labels: ready
