### ISSUE TITLE
Only update document TEI when marked reviewed

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#89] opened 2017-09-20 18:50 UTC
TEI documents that have been reviewed have also had all entities approved.  As a result, we need to hold off on updating document TEI until the document has been reviewed, in order to make sure we don't have bad/unapproved links.

**Comment by benwbrum** [comment] 2017-09-22 14:36
Duplicate of #91

**Closed by benwbrum** 2017-09-22 14:36 UTC
